# Generated by Django 4.0 on 2022-01-17 18:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nome')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ')),
                ('email', models.EmailField(max_length=50)),
                ('status', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=90, verbose_name='Endereço')),
                ('city', models.CharField(max_length=30, verbose_name='Cidade')),
                ('managers', models.ManyToManyField(blank=True, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Company',
            },
        ),
    ]
